layout_spectrum: 0.07552349938264136
typography_spectrum: 0.3357385994564041
color:
  lightness: 0.8789691339872113
  brandColors:
    - '#111107'
    - '#78B2FC'
    - '#4062A1'
    - '#B6E3FF'
    - '#869740'
  saturation: 0.04549906674348334
  brandStrength: 0.09396921737396186
  rhythmicContrast: 0.9559188858924046
content_rating:
  adult: false
github: true
opengraph: {}
analytics: {}
author: {}
name: Testcat
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: IDEEËNBOX
    id: 7c844baa-a8f1-4a7e-96be-8e2a0317fe01
    type: content
  - name: Hoe staan de werken ?
    id: 29e5579b-983d-4561-957c-55646045d290
    type: content
  - name: Lift it up
    id: fa502acf-8c87-460a-8e5e-00773aa67d73
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Bouwfonds GENT
content: []
description: LECTORIUM ROSICRUCIANUM   samen sterk in 1-heid
purpose:
  - type: email
    url: 'mailto:LRbouwfondsGent@gmail.com'
    label: Mail hier je ideeën !
