typography_spectrum: 0.7763302633813629
content_rating:
  adult: false
color:
  lightness: 0.7503241935127074
  brandColors:
    - '#111107'
    - '#78B2FC'
    - '#4062A1'
    - '#B6E3FF'
    - '#869740'
  saturation: 0.3383477292509547
  brandStrength: 0.5895483654589013
  rhythmicContrast: 0.3501189789739391
github: true
opengraph: {}
layout_spectrum: 0.07795972222084235
analytics: {}
author: {}
name: Testcat
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: IDEEËNBOX
    id: 7c844baa-a8f1-4a7e-96be-8e2a0317fe01
    type: content
  - name: Hoe staan de werken ?
    id: 29e5579b-983d-4561-957c-55646045d290
    type: content
  - name: Lift it up
    id: fa502acf-8c87-460a-8e5e-00773aa67d73
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Bouwfonds GENT
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F5HnnSCa7jRQ%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D5HnnSCa7jRQ&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F5HnnSCa7jRQ%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Lectorium Rosicrucianum
          url: 'https://www.youtube.com/user/LectoriumRotterdam'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - verlangen
        - heimwee
        - zen
        - gnosis
        - religie
        - rozenkruis
        - geestesschool van het gouden rozenkruis
        - bezinning
        - bewustwording
        - inzicht
        - verlossing
        - pad
        - weg
        - ziele...
      description: >-
        DE KRACHT VAN HET VERLANGEN Bezinningsbijeenkomst IN OKTOBER 2015
        toegang gratis - 20.00u tot 20.45u "Als het hart voortdurend is - vol
        van begeerten en aardse gerichtheden - kan men alleen begrensde, eindige
        vormen zien." (uit de Daodejing) Tijdens deze bezinningsbijeenkomst
        staan we stil bij de rol die het verlangen speelt in ons leven.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=5HnnSCa7jRQ&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=5HnnSCa7jRQ&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=5HnnSCa7jRQ&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=5HnnSCa7jRQ&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=5HnnSCa7jRQ&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=5HnnSCa7jRQ'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=5HnnSCa7jRQ
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=5HnnSCa7jRQ
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=5HnnSCa7jRQ'
      title: De Kracht van het Verlangen
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b5f280d0-a65b-4b44-b275-a20754fc427a.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b5f280d0-a65b-4b44-b275-a20754fc427a.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/22fb4146-8664-435a-981b-e55706910648.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/22fb4146-8664-435a-981b-e55706910648.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: LECTORIUM ROSICRUCIANUM   samen sterk in 1-heid
purpose:
  - type: email
    url: 'mailto:LRbouwfondsGent@gmail.com'
    label: Mail hier je ideeën !
